@startuml

actor User as user
participant "Vinmart" as vinmart
participant "API Server" as apiServer
participant "Cloud Storage Service" as cloudStorageService
database Database as database

group Successful case

user -> vinmart : User access to home screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: GET \nEndpoint: /api/v1/catalogue/products\nHeader: { authorization }\nPayload: {}

activate apiServer

apiServer ->> database : Query "Product" table joined with "Image" table \nby "productId" attribute

activate database

database -->> apiServer : Return all products included image

deactivate database

apiServer -->> vinmart : [*] Get all products success\nResponse\nMethod: GET \nEndpoint: /api/v1/catalogue/products\nStatus: 200\nPayload: { products }

deactivate apiServer

vinmart --> user : Render products list to screen 

deactivate vinmart

end

group Successful case

user -> vinmart : User access to admin screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nHeader: { authorization }\nPayload: { categoryId, productUnitId, name, \nprice, description, quantityStock, images }

activate apiServer

apiServer ->> database : Query "Product" table by "name" attribute

activate database

database -->> apiServer : Cannot found record

apiServer ->> database : Query "Category" table by "categoryId" attribute

database -->> apiServer : Found record

apiServer ->> database : Query "Product Unit" table by "productUnitId" attribute

database -->> apiServer : Found record

group Asynchronous - Upload Image to Cloud Storage

apiServer ->> cloudStorageService: Send received images from client \nto cloud storage service

activate cloudStorageService

cloudStorageService -->> apiServer: Response success & return uploaded image URLs

deactivate cloudStorageService

end

apiServer ->> database : Create new product with inputted values

database -->> apiServer : Return created product

deactivate database

apiServer -->> vinmart : [*] Created new product success\nResponse\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nStatus: 200\nPayload: { id, categoryId, productUnitId, name, \nprice, description, quantityStock, images, \ncreatedAt, updatedAt }

deactivate apiServer

vinmart --> user : Render products list to screen 

deactivate vinmart

else Failure case 1

user -> vinmart : User access to admin screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nHeader: { authorization }\nPayload: { categoryId, productUnitId, name, \nprice, description, quantityStock, images }

activate apiServer

apiServer -->> vinmart : [*] Uploaded file with unsupported media type\nResponse\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nStatus: 415\nPayload: { errors }

deactivate apiServer

vinmart --> user : Dispay Error Message\nMessage: The image uploaded with wrong media type

deactivate vinmart

else Failure case 2

user -> vinmart : User access to admin screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nHeader: { authorization }\nPayload: { categoryId, productUnitId, name, \nprice, description, quantityStock, images }

activate apiServer

apiServer -->> vinmart : [*] Uploaded file too large\nResponse\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nStatus: 413\nPayload: { errors }

deactivate apiServer

vinmart --> user : Dispay Error Message\nMessage: The image uploaded with too large size

deactivate vinmart

else Failure case 3

user -> vinmart : User access to admin screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nHeader: { authorization }\nPayload: { categoryId, productUnitId, name, \nprice, description, quantityStock, images }

activate apiServer

apiServer ->> database : Query "Product" table by "name" attribute

activate database

database -->> apiServer : Found record

deactivate database

apiServer -->> vinmart : [*] Entered "name" is already registered\nResponse\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nStatus: 409\nPayload: { errors }

deactivate apiServer

vinmart --> user : Dispay Error Message\nMessage: Name already registered

deactivate vinmart

else Failure case 4

user -> vinmart : User access to admin screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nHeader: { authorization }\nPayload: { categoryId, productUnitId, name, \nprice, description, quantityStock, images }

activate apiServer

apiServer ->> database : Query "Product" table by "name" attribute

activate database

database -->> apiServer : Cannot found record

apiServer ->> database : Query "Category" table by "categoryId" attribute

database -->> apiServer : Cannot found record

deactivate database

apiServer -->> vinmart : [*] Entered "categoryId" is not registered\nResponse\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nStatus: 400\nPayload: { errors }

deactivate apiServer

vinmart --> user : Dispay Error Message\nMessage: Category is not registered

deactivate vinmart

else Failure case 5

user -> vinmart : User access to admin screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nHeader: { authorization }\nPayload: { categoryId, productUnitId, name, \nprice, description, quantityStock, images }

activate apiServer

apiServer ->> database : Query "Product" table by "name" attribute

activate database

database -->> apiServer : Cannot found record

apiServer ->> database : Query "Category" table by "categoryId" attribute

database -->> apiServer : Found record

apiServer ->> database : Query "Product Unit" table by "productUnitId" attribute

database -->> apiServer : Cannot found record

deactivate database

apiServer -->> vinmart : [*] Entered "productUnitId" is not registered\nResponse\nMethod: POST \nEndpoint: /api/v1/catalogue/products\nStatus: 400\nPayload: { errors }

deactivate apiServer

vinmart --> user : Dispay Error Message\nMessage: Product Unit is not registered

deactivate vinmart

end

@enduml