@startuml

top to bottom direction

actor "[1] - User" as user
database "[4] - Database" as database

package "Vinmart Service" {
  node "[3] - Authentication Service" as authenticationService

  node "[2] - Catalogue Service" {
    component "[5] - API Server" as apiServer
    component "[6] - Search Service" as searchService

    apiServer -up-> searchService
    apiServer -down-> authenticationService
  }

  authenticationService -down-> apiServer

  user -right-> apiServer
  apiServer -right-> database
}

@enduml