@startuml

actor User as user
participant "Vinmart" as vinmart
participant "API Server" as apiServer
database Database as database

group Successful case

user -> vinmart : User access to update profile screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: PATCH \nEndpoint: /api/v1/users/:userId/password\nHeader: { authorization }\nPayload: { currentPassword, newPassword, confirmPassword }

activate apiServer

apiServer ->> database : Query "User" table by "id" attribute

activate database

database -->> apiServer : Return user to compare old password

apiServer ->> database : Update new user's password with received value

database -->> apiServer : Response success

deactivate database

apiServer -->> vinmart : [*] Update user's password success\nResponse\nMethod: PATCH \nEndpoint: /api/v1/users/:userId/password\nStatus: 200\nPayload: {}

deactivate apiServer

vinmart --> user : Redirect to Setting screen

deactivate vinmart

else Failure case 1

user -> vinmart : User access to update profile screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: PATCH \nEndpoint: /api/v1/users/:userId/password\nHeader: { authorization }\nPayload: { currentPassword, newPassword, confirmPassword }

activate apiServer

apiServer ->> database : Query "User" table by "id" attribute

activate database

database -->> apiServer : Return user to compare old password

deactivate database

apiServer -->> vinmart : [*] Current password is incorrect\nResponse\nMethod: PATCH \nEndpoint: /api/v1/users/:userId/password\nStatus: 400\nPayload: { errors }

deactivate apiServer

vinmart --> user : Dispay Error Message\nMessage: The current password is incorrect.

deactivate vinmart

else Failure case 2

user -> vinmart : User access to update profile screen

activate vinmart

vinmart ->> apiServer : Request\nMethod: PATCH \nEndpoint: /api/v1/users/:userId/password\nHeader: { authorization }\nPayload: { currentPassword, newPassword, confirmPassword }

activate apiServer

apiServer -->> vinmart : [*] New password cannot be same as current password\nResponse\nMethod: PATCH \nEndpoint: /api/v1/users/:userId/password\nStatus: 400\nPayload: { errors }

deactivate apiServer

vinmart --> user : Dispay Error Message\nMessage: New password cannot be same as current password

deactivate vinmart

end

@enduml